#Now I am reading 200000 lines per file.
#When I tried there was a problem in the task 5 with 200000 lines
#To see all the tasks properly please go to project2_2.c
#just change the defined NUMBEROFLINESREAD to 100000 or less

# To run task 1:
1:
	gcc -w -o project2_1 project2_1.c -lpthread
	time ./project2_1 1
# To run task 1 to merge tries:
11:
	gcc -w -o project2_1 project2_1.c -lpthread
	time ./project2_1 11
# To run task 2:
2:
	gcc -w -o project2_2 project2_2.c -lpthread
	time ./project2_2 2

# To run task 3:
3:
	gcc -w -o project2_2 project2_2.c -lpthread
	time ./project2_2 3

# To run task 4:
4:
	gcc -w -o project2_2 project2_2.c -lpthread
	time ./project2_2 4

# To run task 5:
5:
	gcc -w -o project2_2 project2_2.c -lpthread
	time ./project2_2 5

# To run task 6:
6:
	gcc -w -o project2_2 project2_2.c -lpthread
	time ./project2_2 6

# To run task 7:
7:
	gcc -w -o project2_2 project2_2.c -lpthread
	time ./project2_2 7

# After every execution in order to delete the file created "Dictionary.txt"
rd:
	rm Dictionary.txt
	clear